#pragma once
class ActionEnums
{
public:
	ActionEnums();
	~ActionEnums();

	enum ActionEnumValues
	{ 
		SHOWDESCRIPTION,
		NEXTDESCRIPTION,
		PREVDESCRIPTION,
		SHOWMENU,
		NEWGROUP,
		NEWGROUPSELECTION,
		TOGGLEFILELOGGING,
		TOGGLEOUTPUTDEBUGSTRING,
		CLOSEWINDOW,
		NEXTTABCONTROL,
		PREVTABCONTROL,
		SHOWGROUPS,
		NEWCLIP,
		EDITCLIP,
		SELECTIONUP,
		SELECTIONDOWN,
		MOVEFIRST,
		MOVELAST,
		CANCELFILTER,
		HOMELIST,
		BACKGRROUP,
		TOGGLESHOWPERSISTANT,
		PASTE_SELECTED,
		DELETE_SELECTED,
		CLIP_PROPERTIES,
		PASTE_SELECTED_PLAIN_TEXT,
		MOVE_CLIP_TO_GROUP,
		ELEVATE_PRIVlEGES,
		SHOW_IN_TASKBAR,
		COMPARE_SELECTED_CLIPS,
		SELECT_LEFT_SIDE_COMPARE,
		SELECT_RIGHT_SITE_AND_DO_COMPARE,
		EXPORT_TO_TEXT_FILE,
		EXPORT_TO_QR_CODE,
		EXPORT_TO_GOOGLE_TRANSLATE,
		EXPORT_TO_BITMAP_FILE,
		SAVE_CURRENT_CLIPBOARD,
		MOVE_CLIP_UP,
		MOVE_CLIP_DOWN,
		MOVE_CLIP_TOP,
		FILTER_ON_SELECTED_CLIP,
		PASTE_UPPER_CASE,
		PASTE_LOWER_CASE,
		PASTE_CAPITALiZE,
		PASTE_SENTENCE_CASE,
		PASTE_REMOVE_LINE_FEEDS,
		PASTE_ADD_ONE_LINE_FEED,
		PASTE_ADD_TWO_LINE_FEEDS,
		PASTE_TYPOGLYCEMIA

	};
};

