#pragma once
class ActionEnums
{
public:
	ActionEnums();
	~ActionEnums();

	enum ActionEnumValues{ 
		SHOWDESCRIPTION,
		NEXTDESCRIPTION,
		PREVDESCRIPTION,
		SHOWMENU,
		NEWGROUP,
		NEWGROUPSELECTION,
		TOGGLEFILELOGGING,
		TOGGLEOUTPUTDEBUGSTRING,
		CLOSEWINDOW,
		NEXTTABCONTROL,
		PREVTABCONTROL,
		SHOWGROUPS,
		NEWCLIP,
		EDITCLIP,
		SELECTIONUP,
		SELECTIONDOWN,
		MOVEFIRST,
		MOVELAST,
		CANCELFILTER,
		HOMELIST,
		BACKGRROUP,
		TOGGLESHOWPERSISTANT,
		PASTE_SELECTED,
		DELETE_SELECTED,
		CLIP_PROPERTIES,
		PASTE_SELECTED_PLAIN_TEXT,
		MOVE_CLIP_TO_GROUP,
		ELEVATE_PRIVlEGES,
	};
};

