//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CP_Main.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_CP_MAITYPE                  129
#define IDR_EDIT_WND                    129
#define IDR_MENU                        130
#define IDD_SELECT_DB                   131
#define IDD_OPTIONS_STATS               132
#define IDD_ADD_TYPE                    134
#define IDD_COPY_PROPERTIES             135
#define IDD_ABOUT                       136
#define IDD_GROUP_NAME                  138
#define IDB_CLOSED_FOLDER               141
#define IDB_CLOSED_FOLDER_PRESSED       142
#define IDB_CLOSED_FOLDER_FOCUSED       143
#define IDB_OPEN_FOLDER                 144
#define IDB_OPEN_FOLDER_FOCUSED         145
#define IDB_OPEN_FOLDER_PRESSED         146
#define IDB_BACK                        147
#define IDB_BACK_PRESSED                148
#define IDD_OPTIONS_FRIENDS             148
#define IDB_BACK_FOCUSED                149
#define IDI_DITTO_NOCOPYCB              150
#define IDD_FRIEND_DETAILS              152
#define IDD_MOVE_TO_GROUP               156
#define IDD_DIALOG_REMOTE_FILE          157
#define IDR_FILE_COPY                   158
#define IDD_OPTIONS_COPY_BUFFERS        166
#define IDI_ICON1                       167
#define IDD_DIALOG1                     168
#define IDD_GLOBAL_CLIPS                168
#define IDB_BITMAP_SEARCH_NORMAL        170
#define IDB_BITMAP_SEARCH_CLOSE         171
#define IDB_BITMAP1                     172
#define IDB_BITMAP_SEARCH_NORMAL_125    172
#define IDB_BITMAP_SEARCH_CLOSE_125     173
#define IDB_BITMAP2                     174
#define IDB_BITMAP_SEARCH_CLOSE_150     174
#define IDB_BITMAP_SEARCH_NORMAL_150    175
#define IDB_BITMAP_SEARCH_CLOSE_200     176
#define IDB_BITMAP_SEARCH_NORMAL_151    177
#define IDB_BITMAP_SEARCH_NORMAL_200    177
#define IDC_PATH                        1000
#define IDC_GET_PATH                    1001
#define IDC_SELECT_SOUND                1002
#define IDC_SELECT                      1003
#define IDC_TRIP_COPIES                 1004
#define IDC_TRIP_PASTES                 1005
#define IDC_RESET_COUNTS                1006
#define IDC_ALL_COPIES                  1007
#define IDC_ALL_PASTES                  1008
#define IDC_TRIP_DATE                   1009
#define IDC_EDIT_ALL_DATE               1010
#define IDC_SAVED_COPIES                1011
#define IDC_SAVED_COPY_DATA             1012
#define IDC_REMOVE_ALL                  1013
#define IDC_DATABASE_SIZE               1014
#define IDC_LIST1                       1014
#define IDC_ADD                         1015
#define IDC_CHECK_SEND_ALL              1015
#define IDC_CLIPS_SENT                  1015
#define IDC_DELETE                      1016
#define IDC_EDIT_IP                     1016
#define IDC_CLIPS_RECIVED               1016
#define IDC_EDIT1                       1017
#define IDC_EDIT_DESCRIPTION            1017
#define IDC_LAST_STARTED                1017
#define IDC_LIST2                       1018
#define IDC_EDIT_APP_COPY_EXCLUDE       1018
#define IDC_ADD_1                       1019
#define IDC_ADD_2                       1020
#define IDC_EDIT_DISPLAY_TEXT           1020
#define IDC_ADD_3                       1021
#define IDC_DELETE_COPY_DATA            1021
#define IDC_DATE                        1022
#define IDC_COPY_DATA                   1023
#define IDC_DATE2                       1024
#define IDC_DATE_LAST_USED              1024
#define IDC_NEVER_AUTO_DELETE           1025
#define IDC_NAMED_COPY                  1026
#define IDC_HOT_KEY_GLOBAL              1026
#define IDC_COMPACT_REPAIR              1027
#define IDC_NAMED_PASTE                 1027
#define IDC_BT_COMPACT_AND_REPAIR       1028
#define IDC_CHECK_UPDATES               1029
#define IDC_CHECK_FOR_UPDATES           1030
#define IDC_LIST                        1032
#define IDC_CTRL_CLICK                  1033
#define IDC_SET_DB_PATH                 1034
#define IDC_SHOW_TEXT_FOR_FIRST_TEN_HOT_KEYS 1034
#define IDC_USE_DEFAULT                 1035
#define IDC_CTRL_CLICK2                 1035
#define IDC_HYPER_LINK                  1036
#define IDC_ALLOW_DUPLICATES            1037
#define IDC_UPDATE_TIME_ON_PASTE        1038
#define IDC_SAVE_MULTIPASTE             1039
#define IDC_BUTTON1                     1040
#define IDC_PARSE_BUTTON                1040
#define IDC_HIDE_DITO_ON_HOT_KEY        1040
#define IDC_BUTTON_FONT                 1040
#define IDC_BUTTON_NEW_GROUP            1040
#define IDC_BUTTON_REFRESH              1040
#define IDC_PARSE_EDIT                  1041
#define IDC_SEND_PASTE_MESSAGE          1041
#define IDC_BUTTON_PROPERTIES           1041
#define IDC_CHECK1                      1042
#define IDC_HISTORY_START_TOP           1042
#define IDC_CHECK_SEND_PASTE            1042
#define IDC_CHECK_LOG_SEND_RECIEVE      1042
#define IDC_ENSURE                      1042
#define IDC_PLAY_SOUND_1                1042
#define IDC_PLAY_SOUND_2                1043
#define IDC_PLAY_SOUND_3                1044
#define IDD_OPTIONS_KEYSTROKES          2001
#define IDC_HOTKEY                      2002
#define IDC_DISPLAY_IN_SYSTEMTRAY       2003
#define IDD_OPTIONS_GENERAL             2003
#define IDC_HOTKEY_TEXT_ONLY            2003
#define IDD_OPTIONS_TYPES               2004
#define IDC_START_ON_STARTUP            2004
#define IDR_QUICK_PASTE                 2005
#define IDC_TRANSPARENCY                2006
#define IDD_OPTIONS_QUICK_PASTE         2006
#define IDD_OPTIONS_UTILITIES           2007
#define IDC_TRANS_PERC                  2007
#define IDC_MAXIMUM                     2008
#define IDC_EXPIRE                      2009
#define IDC_EXPIRE_AFTER                2010
#define IDC_DESC_TEXT_SIZE              2011
#define IDC_MAX_SAVED_COPIES            2012
#define IDC_LINES_ROW                   2013
#define IDC_AT_CARET                    2015
#define IDC_AT_CURSOR                   2016
#define IDC_AT_PREVIOUS                 2017
#define IDC_COMPACT_DB                  2018
#define IDC_REPAIR                      2019
#define IDC_DESC_SHOW_LEADING_WHITESPACE 2021
#define IDC_NAME                        2022
#define IDC_SHOW_THUMBNAILS             2022
#define IDC_COMBO1                      2023
#define IDC_DRAW_RTF                    2023
#define IDC_HOTKEY1                     2024
#define IDC_HOTKEY2                     2025
#define IDC_EDIT_PLACE_ON_CLIPBOARD     2025
#define IDC_HOTKEY3                     2026
#define IDC_CHECK_DISABLE_FRIENDS       2026
#define IDC_HOTKEY4                     2027
#define IDC_TREE                        2027
#define IDC_HOTKEY5                     2028
#define IDC_RICHEDIT1                   2028
#define IDC_HOTKEY6                     2029
#define IDC_STATIC_FORMATS              2029
#define IDC_HOTKEY7                     2030
#define IDC_HOTKEY8                     2031
#define IDC_BUTTON_DEFAULT_FAULT        2031
#define IDC_HOTKEY9                     2032
#define IDC_EDIT_PASSWORD               2032
#define IDC_HOTKEY10                    2033
#define IDC_EDIT_PLAY_SOUND             2033
#define IDC_BUTTON_PLAY                 2034
#define IDC_CHECK_WIN_DITTO             2035
#define IDC_CHECK_WIN_NAMED_COPY        2036
#define IDC_CHECK_FIND_AS_YOU_TYPE      2036
#define IDC_CHECK_WIN_TEXT              2036
#define IDC_CHECK_WIN_TEXT_ONLY         2036
#define IDC_CHECK_WIN6                  2037
#define IDC_CHECK_ENTIRE_WINDOW_IS_VISIBLE 2037
#define IDC_EDIT_ADDITIONAL             2037
#define IDC_CHECK_WIN7                  2038
#define IDC_CHECK_SHOW_ALL_IN_MAIN_LIST 2038
#define IDC_EDIT_MAX_SIZE               2038
#define IDC_CHECK_WIN8                  2039
#define IDC_STATIC_HOT_KEY              2039
#define IDC_CHECK_PROMPT_DELETE_CLIP    2039
#define IDC_CHECK_WIN9                  2040
#define IDC_STATIC_DATE                 2040
#define IDC_CHECK_WIN10                 2041
#define IDC_STATIC_MOVE_TO_GROUP        2041
#define IDC_CHECK_WIN1                  2042
#define IDC_STATIC_TITLE                2042
#define IDC_CHECK_WIN2                  2043
#define IDC_STATIC_DAYS                 2043
#define IDC_STATIC_DATE2                2043
#define IDC_CHECK_WIN3                  2044
#define IDC_STATIC_AMOUNT               2044
#define IDC_CHECK_WIN4                  2045
#define IDC_STATIC_SOUND                2045
#define IDC_CHECK_WIN5                  2046
#define IDC_STATIC_MAX_SIZE             2046
#define IDC_STATIC_NO_LIMIT             2047
#define IDC_CHECK_WIN_NAMED_PASTE       2047
#define IDC_STATIC_ACTIVATE             2048
#define IDC_STATIC_NAMED_COPY           2049
#define IDC_STATIC_ACTIVATE2            2049
#define IDC_STATIC_WIN                  2050
#define IDC_STATIC_GROUP                2051
#define IDC_STATIC_1                    2052
#define IDC_STATIC_2                    2053
#define IDC_STATIC_3                    2054
#define IDC_STATIC_4                    2055
#define IDC_STATIC_5                    2056
#define IDC_STATIC_6                    2057
#define IDC_STATIC_7                    2058
#define IDC_STATIC_8                    2059
#define IDC_STATIC_9                    2060
#define IDC_STATIC_10                   2061
#define IDC_STATIC_LINES                2062
#define IDC_STATIC_NAMED_COPY2          2062
#define IDC_STATIC_POPUP                2063
#define IDC_STATIC_LEGEND               2064
#define IDC_STATIC_LEG                  2065
#define IDC_STATIC_11                   2066
#define IDC_STATIC_12                   2067
#define IDC_STATIC_13                   2068
#define IDC_STATIC_LANGUAGE             2069
#define IDC_COMBO_LANGUAGE              2070
#define IDC_EDIT_SAVE_DELAY             2071
#define IDC_STATIC_SAVE_DELAY           2072
#define IDC_BUTTON_ABOUT                2073
#define IDC_EDIT_QUICK_PASTE            2074
#define IDC_STATIC_LINK                 2075
#define IDC_PROGRESS_FILE               2076
#define IDC_PROGRESS_ALL_FILES          2077
#define IDC_FILE_COPY                   2078
#define IDC_STATIC_COPY_1               2079
#define IDC_STATIC_PASTE_1              2080
#define IDC_STATIC_CUT_1                2081
#define IDC_COPY_1                      2082
#define IDC_PASTE_1                     2083
#define IDC_CUT_1                       2084
#define IDC_WIN_COPY_1                  2085
#define IDC_WIN_PASTE_1                 2086
#define IDC_WIN_CUT_1                   2087
#define IDC_BUFFER_GROUP_1              2088
#define IDC_COPY_2                      2089
#define IDC_EDIT_CLIP_SEPARATOR         2089
#define IDC_WIN_COPY_2                  2090
#define IDC_STATIC_CLIP_SEPARATOR       2090
#define IDC_PASTE_2                     2091
#define IDC_STATIC_CUSTOM_KEYS          2091
#define IDC_WIN_PASTE_2                 2092
#define IDC_STATIC_THEME                2092
#define IDC_STATIC_COPY_2               2093
#define IDC_COMBO_THEME                 2093
#define IDC_STATIC_PASTE_2              2094
#define IDC_BUTTON_THEME                2094
#define IDC_CUT_2                       2095
#define IDC_STATIC_INCLUDE_APPS         2095
#define IDC_WIN_CUT_2                   2096
#define IDC_STATIC_EXCLUDE_APPS         2096
#define IDC_STATIC_CUT_2                2097
#define IDC_EDIT_APP_COPY_INCLUDE       2097
#define IDC_BUFFER_GROUP_2              2098
#define IDC_STATIC_APP_SEP_DESC         2098
#define IDC_COPY_3                      2099
#define IDC_CHECK_WIN                   2099
#define IDC_WIN_COPY_3                  2100
#define IDC_EDIT_PROPERTIES             2100
#define IDC_PASTE_3                     2101
#define IDC_WIN_PASTE_3                 2102
#define IDC_STATIC_COPY_3               2103
#define IDC_STATIC_PASTE_3              2104
#define IDC_CUT_3                       2105
#define IDC_WIN_CUT_3                   2106
#define IDC_STATIC_CUT_3                2107
#define IDC_BUFFER_GROUP_3              2108
#define ID_FIRST_OPTION                 32771
#define ID_FIRST_EXIT                   32772
#define ID_FIRST_SHOWQUICKPASTE         32773
#define ID_FIRST_TOGGLECONNECTCV        32774
#define ID_MENU_TOGGLECONNECTCV         32775
#define ID_MENU_PROPERTIES              32776
#define ID_MENU_FIRSTTENHOTKEYS_USECTRLNUM 32777
#define ID_MENU_FIRSTTENHOTKEYS_SHOWHOTKEYTEXT 32778
#define ID_MENU_VIEWCAPTIONBARON        32779
#define ID_VIEWCAPTIONBARON_RIGHT       32780
#define ID_VIEWCAPTIONBARON_BOTTOM      32781
#define ID_VIEWCAPTIONBARON_LEFT        32782
#define ID_VIEWCAPTIONBARON_TOP         32783
#define ID_MENU_ALLWAYSONTOP            32784
#define ID_MENU_LINESPERROW_2           32786
#define ID_MENU_LINESPERROW_3           32787
#define ID_MENU_LINESPERROW_4           32788
#define ID_MENU_LINESPERROW_5           32789
#define ID_MENU_TRANSPARENCY_40         32790
#define ID_MENU_AUTOHIDE                32791
#define ID_MENU_TRANSPARENCY_10         32792
#define ID_MENU_VIEWFULLDESCRIPTION     32793
#define ID_MENU_TRANSPARENCY_15         32794
#define ID_SORT_ASCENDING               32795
#define ID_MENU_TRANSPARENCY_20         32796
#define ID_SORT_DESCENDING              32797
#define ID_MENU_TRANSPARENCY_25         32798
#define ID_MENU_TRANSPARENCY_30         32799
#define ID_MENU_TRANSPARENCY_NONE       32800
#define ID_MENU_DELETE                  32801
#define ID_MENU_POSITIONING_ATCARET     32802
#define ID_MENU_POSITIONING_ATCURSOR    32803
#define ID_MENU_POSITIONING_ATPREVIOUSPOSITION 32804
#define ID_MENU_OPTIONS                 32805
#define ID_MENU_EXITPROGRAM             32806
#define ID_MENU_LINESPERROW_1           32807
#define ID_MENU_TRANSPARENCY_5          32808
#define ID_MENU_QUICKOPTIONS            32809
#define ID_MENU_NEWGROUP                32811
#define ID_MENU_NEWGROUPSELECTION       32812
#define ID_MENU_QUICKOPTIONS_ALLWAYSSHOWDESCRIPTION 32813
#define ID_MENU_QUICKOPTIONS_DOUBLECLICKINGONCAPTION_TOGGLESALWAYSONTOP 32814
#define ID_MENU_QUICKOPTIONS_DOUBLECLICKINGONCAPTION_ROLLUPWINDOW 32815
#define ID_MENU_QUICKOPTIONS_DOUBLECLICKINGONCAPTION_TOGGLESALWAYSSHOWDESCRIPTION 32816
#define ID_MENU_QUICKOPTIONS_PROMPTFORNEWGROUPNAMES 32817
#define ID_MENU_VIEWGROUPS              32819
#define ID_MENU_QUICKPROPERTIES_SETTONEVERAUTODELETE 32820
#define ID_MENU_QUICKPROPERTIES_AUTODELETE 32821
#define ID_MENU_QUICKPROPERTIES_REMOVEHOTKEY 32822
#define ID_MENU_SENTTO_FRIENDONE        32824
#define ID_MENU_SENTTO_FRIEND_TWO       32825
#define ID_MENU_SENTTO_FRIEND_THREE     32826
#define ID_MENU_SENTTO_FRIEND_FORE      32827
#define ID_MENU_SENTTO_FRIEND_FIVE      32828
#define ID_MENU_SENTTO_FRIEND_SIX       32829
#define ID_MENU_SENTTO_FRIEND_SEVEN     32830
#define ID_MENU_SENTTO_FRIEND_EIGHT     32831
#define ID_MENU_SENTTO_FRIEND_NINE      32832
#define ID_MENU_SENTTO_FRIEND_TEN       32833
#define ID_MENU_SENTTO_FRIEND_ELEVEN    32834
#define ID_MENU_SENTTO_FRIEND_TWELVE    32835
#define ID_MENU_SENTTO_FRIEND_THIRTEEN  32836
#define ID_MENU_SENTTO_FRIEND_FORETEEN  32837
#define ID_MENU_SENTTO_FRIEND_FIFTEEN   32838
#define ID_MENU_SENTTO_PROMPTFORIP      32839
#define ID_MENU_GROUPS_MOVETOGROUP      32840
#define ID_MENU_PASTEPLAINTEXTONLY      32841
#define ID_MENU_HELP                    32842
#define ID_FIRST_HELP                   32843
#define ID_MENU_QUICKOPTIONS_FONT       32844
#define ID_MENU_QUICKOPTIONS_SHOWTHUMBNAILS 32845
#define ID_MENU_QUICKOPTIONS_DRAWRTFTEXT 32846
#define ID_MENU_QUICKOPTIONS_PASTECLIPAFTERSELECTION 32847
#define ID_MENU_QUICKOPTIONS_FINDASYOUTYPE 32848
#define ID_MENU_QUICKOPTIONS_ENSUREENTIREWINDOWISVISIBLE 32849
#define ID_MENU_QUICKOPTIONS_SHOWCLIPSTHATAREINGROUPSINMAINLIST 32850
#define ID_MENU_PASTEHTMLASPLAINTEXT    32851
#define ID_QUICKOPTIONS_PROMPTTODELETECLIP 32852
#define ID_MENU_EXPORT                  32853
#define ID_FIRST_IMPORT                 32854
#define ID_MENU_IMPORT                  32855
#define ID_QUICKPROPERTIES_REMOVEQUICKPASTE 32856
#define ID_MENU_EDITITEM                32860
#define ID_BUTTON_SAVE                  32862
#define ID_BUTTON_SAVE_ALL              32863
#define ID_BUTTON_CLOSE                 32864
#define ID_BUTTON_NEW                   32866
#define ID_MENU_NEWCLIP                 32867
#define ID_FIRST_NEWCLIP                32868
#define ID_BUTTON_SAVE_CLOSE_CLIPBOARD  32869
#define ID_FIRST_COPYTODEVICE           32870
#define ID_PASTE_PLAIN_TEXT             32871
#define ID_FIRST_GLOBALHOTKEYS          32872

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        175
#define _APS_NEXT_COMMAND_VALUE         32873
#define _APS_NEXT_CONTROL_VALUE         2101
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
