//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CP_Main.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_CP_MAITYPE                  129
#define IDR_MENU                        130
#define IDD_SELECT_DB                   131
#define IDD_OPTIONS_STATS               132
#define IDD_ADD_TYPE                    134
#define IDD_COPY_PROPERTIES             135
#define IDD_ABOUT                       136
#define IDC_PATH                        1000
#define IDC_GET_PATH                    1001
#define IDC_SELECT                      1003
#define IDC_TRIP_COPIES                 1004
#define IDC_TRIP_PASTES                 1005
#define IDC_RESET_COUNTS                1006
#define IDC_ALL_COPIES                  1007
#define IDC_ALL_PASTES                  1008
#define IDC_TRIP_DATE                   1009
#define IDC_EDIT_ALL_DATE               1010
#define IDC_SAVED_COPIES                1011
#define IDC_SAVED_COPY_DATA             1012
#define IDC_REMOVE_ALL                  1013
#define IDC_DATABASE_SIZE               1014
#define IDC_LIST1                       1014
#define IDC_ADD                         1015
#define IDC_DELETE                      1016
#define IDC_EDIT1                       1017
#define IDC_LIST2                       1018
#define IDC_ADD_1                       1019
#define IDC_ADD_2                       1020
#define IDC_EDIT_DISPLAY_TEXT           1020
#define IDC_ADD_3                       1021
#define IDC_DELETE_COPY_DATA            1021
#define IDC_DATE                        1022
#define IDC_COPY_DATA                   1023
#define IDC_NEVER_AUTO_DELETE           1025
#define IDC_NAMED_COPY                  1026
#define IDC_COMPACT_REPAIR              1027
#define IDC_BT_COMPACT_AND_REPAIR       1028
#define IDC_CHECK_UPDATES               1029
#define IDC_CHECK_FOR_UPDATES           1030
#define IDC_LIST                        1032
#define IDC_CTRL_CLICK                  1033
#define IDC_SET_DB_PATH                 1034
#define IDC_SHOW_TEXT_FOR_FIRST_TEN_HOT_KEYS 1034
#define IDC_USE_DEFAULT                 1035
#define IDC_CTRL_CLICK2                 1035
#define IDC_HYPER_LINK                  1036
#define IDC_ALLOW_DUPLICATES            1037
#define IDC_UPDATE_TIME_ON_PASTE        1038
#define IDC_SAVE_MULTIPASTE             1039
#define IDC_BUTTON1                     1040
#define IDC_PARSE_BUTTON                1040
#define IDC_PARSE_EDIT                  1041
#define IDC_CHECK1                      1042
#define IDC_HISTORY_START_TOP           1042
#define IDD_OPTIONS_KEYSTROKES          2001
#define IDC_HOTKEY                      2002
#define IDC_DISPLAY_IN_SYSTEMTRAY       2003
#define IDD_OPTIONS_GENERAL             2003
#define IDD_OPTIONS_TYPES               2004
#define IDC_START_ON_STARTUP            2004
#define IDR_QUICK_PASTE                 2005
#define IDC_TRANSPARENCY                2006
#define IDD_OPTIONS_QUICK_PASTE         2006
#define IDD_OPTIONS_UTILITIES           2007
#define IDC_TRANS_PERC                  2007
#define IDC_MAXIMUM                     2008
#define IDC_EXPIRE                      2009
#define IDC_EXPIRE_AFTER                2010
#define IDC_DESC_TEXT_SIZE              2011
#define IDC_MAX_SAVED_COPIES            2012
#define IDC_LINES_ROW                   2013
#define IDC_AT_CARET                    2015
#define IDC_AT_CURSOR                   2016
#define IDC_AT_PREVIOUS                 2017
#define IDC_COMPACT_DB                  2018
#define IDC_REPAIR                      2019
#define IDC_DESC_SHOW_LEADING_WHITESPACE 2021
#define ID_FIRST_OPTION                 32771
#define ID_FIRST_EXIT                   32772
#define ID_FIRST_SHOWQUICKPASTE         32773
#define ID_FIRST_RECONNECTTOCLIPBOARDCHAIN 32774
#define ID_MENU_RECONNECTTOCLIPBOARDCHAIN 32775
#define ID_MENU_PROPERTIES              32776
#define ID_MENU_FIRSTTENHOTKEYS_USECTRLNUM 32777
#define ID_MENU_FIRSTTENHOTKEYS_SHOWHOTKEYTEXT 32778
#define ID_MENU_VIEWCAPTIONBARON        32779
#define ID_VIEWCAPTIONBARON_RIGHT       32780
#define ID_VIEWCAPTIONBARON_BOTTOM      32781
#define ID_VIEWCAPTIONBARON_LEFT        32782
#define ID_VIEWCAPTIONBARON_TOP         32783
#define ID_MENU_ALLWAYSONTOP            32784
#define ID_MENU_LINESPERROW_2           32786
#define ID_MENU_LINESPERROW_3           32787
#define ID_MENU_LINESPERROW_4           32788
#define ID_MENU_LINESPERROW_5           32789
#define ID_MENU_TRANSPARENCY_40         32790
#define ID_MENU_AUTOHIDE                32791
#define ID_MENU_TRANSPARENCY_10         32792
#define ID_MENU_VIEWFULLDESCRIPTION     32793
#define ID_MENU_TRANSPARENCY_15         32794
#define ID_SORT_ASCENDING               32795
#define ID_MENU_TRANSPARENCY_20         32796
#define ID_SORT_DESCENDING              32797
#define ID_MENU_TRANSPARENCY_25         32798
#define ID_MENU_TRANSPARENCY_30         32799
#define ID_MENU_TRANSPARENCY_NONE       32800
#define ID_MENU_DELETE                  32801
#define ID_MENU_POSITIONING_ATCARET     32802
#define ID_MENU_POSITIONING_ATCURSOR    32803
#define ID_MENU_POSITIONING_ATPREVIOUSPOSITION 32804
#define ID_MENU_OPTIONS                 32805
#define ID_MENU_EXITPROGRAM             32806
#define ID_MENU_LINESPERROW_1           32807
#define ID_MENU_TRANSPARENCY_5          32808
#define ID_MENU_QUICKOPTIONS            32809
#define ID_MENU_NEWGROUP                32811
#define ID_MENU_NEWGROUPSELECTION       32812
#define ID_MENU_QUICKOPTIONS_ALLWAYSSHOWDESCRIPTION 32813
#define ID_MENU_QUICKOPTIONS_DOUBLECLICKINGONCAPTION_TOGGLESALWAYSONTOP 32814
#define ID_MENU_QUICKOPTIONS_DOUBLECLICKINGONCAPTION_ROLLUPWINDOW 32815
#define ID_MENU_QUICKOPTIONS_DOUBLECLICKINGONCAPTION_TOGGLESALWAYSSHOWDESCRIPTION 32816

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32817
#define _APS_NEXT_CONTROL_VALUE         2022
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
